spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /templates
      suffix: .html
# log config
logging:
  config: classpath:logback-spring.xml


  # mybatis配置
mybatis:
  type-aliases-package: com.ss.graduation.bean
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

